/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface Addresses {
  barangay: string | null;
  cityMunicipality: string;
  createdAt: Generated<string>;
  deletedAt: string | null;
  id: Generated<number>;
  province: string;
  region: string;
  street: string | null;
  updatedAt: string | null;
  zipCode: string;
}

export interface EmergencyContactAddresses {
  addressId: number | null;
  createdAt: Generated<string>;
  emergencyContactId: number | null;
  isPrimary: number;
  updatedAt: string | null;
}

export interface EmergencyContactPhoneNumbers {
  createdAt: Generated<string>;
  emergencyContactId: number | null;
  isPrimary: number;
  phoneNumberId: number | null;
  updatedAt: string | null;
}

export interface EmergencyContacts {
  createdAt: Generated<string>;
  deletedAt: string | null;
  email: string | null;
  firstName: string;
  id: Generated<number>;
  lastName: string | null;
  middleName: string | null;
  patientId: number;
  relationship: string;
  updatedAt: string | null;
}

export interface PatientAddresses {
  addressId: number | null;
  createdAt: Generated<string>;
  isPrimary: number;
  patientId: number | null;
  updatedAt: string | null;
}

export interface PatientPhoneNumbers {
  createdAt: Generated<string>;
  isPrimary: number;
  patientId: number | null;
  phoneNumberId: number | null;
  updatedAt: string | null;
}

export interface Patients {
  bloodType: string | null;
  civilStatus: string | null;
  createdAt: Generated<string>;
  deletedAt: string | null;
  dob: string | null;
  email: string | null;
  firstName: string;
  id: Generated<number>;
  lastName: string | null;
  middleName: string | null;
  mrn: string;
  sex: string;
  updatedAt: string | null;
}

export interface PhoneNumbers {
  countryCallingCode: string;
  countryCode: string;
  createdAt: Generated<string>;
  deletedAt: string | null;
  e164: string;
  id: Generated<number>;
  raw: string;
  updatedAt: string | null;
}

export interface DB {
  addresses: Addresses;
  emergencyContactAddresses: EmergencyContactAddresses;
  emergencyContactPhoneNumbers: EmergencyContactPhoneNumbers;
  emergencyContacts: EmergencyContacts;
  patientAddresses: PatientAddresses;
  patientPhoneNumbers: PatientPhoneNumbers;
  patients: Patients;
  phoneNumbers: PhoneNumbers;
}
